"""
Pydantic Schemas for Chatbot API requests and responses.
"""
from typing import List, Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, max_length=1000, description="The user's query string.")


class ChatResponse(BaseModel):
    answer: str = Field(..., description="Conversational answer generated by the assistant.")
    sources: List[str] = Field(default_factory=list, description="Source documents or databases referenced.")
    intent: Optional[str] = Field(default=None, description="Detected query intent category.")
    conversation_id: str = Field(..., description="Unique user/conversation identifier for memory tracking.")